# Generated by Django 4.2.8 on 2025-01-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('TitleName', models.CharField(max_length=30)),
                ('HasPassport', models.BooleanField(default=True)),
                ('Salary', models.IntegerField()),
                ('BirthDate', models.DateField()),
                ('HireDate', models.DateField()),
                ('Notes', models.CharField(max_length=200)),
                ('Country', models.CharField(choices=[('IND', 'INDIA'), ('USA', 'United States Of America'), ('UK', 'United Kingdom'), ('AUS', 'AUSTRALIA'), ('AU', 'AUSTRIA'), ('SP', 'SPAIN')], default=None, max_length=35)),
                ('Email', models.EmailField(default='', max_length=50)),
                ('PhoneNumber', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
