# Generated by Django 4.2.8 on 2025-01-18 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeptName', models.CharField(max_length=30)),
                ('LocationName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PartTimeEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('TitleName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.country')),
            ],
        ),
        migrations.CreateModel(
            name='OnSiteEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.city')),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.country')),
                ('state', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.state')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('TitleName', models.CharField(max_length=30)),
                ('HasPassport', models.BooleanField(default=True)),
                ('Salary', models.IntegerField()),
                ('BirthDate', models.DateField()),
                ('HireDate', models.DateField()),
                ('Notes', models.CharField(max_length=200)),
                ('Email', models.EmailField(default='', max_length=50)),
                ('PhoneNumber', models.CharField(default='', max_length=20)),
                ('EmpCountry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Countries', to='PayRollApp.country')),
                ('EmpDepartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Departments', to='PayRollApp.department')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.state'),
        ),
    ]
