# Generated by Django 4.2.8 on 2025-01-13 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PayRollApp', '0003_remove_employee_country_alter_country_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='EmpCountry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Countries', to='PayRollApp.country'),
        ),
        migrations.AddField(
            model_name='employee',
            name='EmpDepartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Departments', to='PayRollApp.department'),
        ),
    ]
