# Generated by Django 4.2.8 on 2025-01-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayRollApp', '0004_employee_empcountry_employee_empdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartTimeEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('TitleName', models.CharField(max_length=30)),
            ],
        ),
    ]
