# Generated by Django 4.2.8 on 2025-01-16 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PayRollApp', '0005_parttimeemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.country')),
            ],
        ),
        migrations.CreateModel(
            name='OnSiteEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.city')),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.country')),
                ('state', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.state')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.state'),
        ),
    ]
